[project]
name = "ai-agent-quest-platform"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.agent-identity-registry]
path = "contracts/agent-identity-registry.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["nft-trait"]


[contracts.quest-registry]
path = "contracts/quest-registry.clar"
clarity_version = 2
epoch = 2.5
depends_on = []


[contracts.reputation-registry]
path = "contracts/reputation-registry.clar"
clarity_version = 2
epoch = 2.5
depends_on = []


[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.x402-quest-escrow]
path = "contracts/x402-quest-escrow.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["sip-010-trait"]

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
